### ISSUE TITLE
 pidFilter et vidFilter

### ISSUE THREAD

**Issue by dewiweb** [benkuper/Launchkey-Mini-Chataigne-Module#1]
Bonjour Ben,
Je risque de te solliciter régulièrement (je tente le développement d'un module Berhinger Xtouch extender...).
Les pidFilter et vidFilter du js correspondent aux identifier USB du launchkey?
Si oui, sont-ils optionnels ou essentiels dans le js ?(je suis dans le cas d'une connection en rtpmidi).

**Comment by benkuper** [comment]
Salut,
pas de problème :)
les pid et vid correspondent bien aux identifiants, et ils ne sont pas nécessaires, ils permettent juste de filtrer la liste des devices au moment de choisir dans l'interface.
