### ISSUE TITLE
how to test an home made module on ubuntu!

### ISSUE THREAD

**Issue by dewiweb** [benkuper/Launchkey-Mini-Chataigne-Module#2]
Ben,
Comment puis-je tester le developpement du module que je développe sous ubuntu avec les appimage de chataigne (compiler à chaque fois risque d'être une purge...surtout que je ne suis pas dev donc je tatonne)?
Dans chataigne tu fait des liens vers les community modules, ne serait-il pas possible de créer un lien éditable vers un dossier local de module?
Si tu as une autre piste je suis preneur...

**Comment by benkuper** [comment]
salut,
il te suffit de mettre ton dossier de module dans le dossier documents/Chataigne/modules . au démarrage, il sera analysé. et ajouté si il est valide. si tu veux changer des choses, il te suffit de faire file > reload custom modules, puis de recharger ta session (CTRL+shift+O)
